[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = ['Shougo/neoinclude.vim', 'Shougo/context_filetype.vim']
on_i = 1
[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c', 'cpp']
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']


