# ↓ここ参照
# http://qiita.com/delphinus35/items/00ff2c0ba972c6e41542
[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'tyru/caw.vim'
[[plugins]]
repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'w0ng/vim-hybrid'
